Model validations
Samuelwanza/ongea pull request #4
Opened 2023-12-01 20:59 UTC by Samuelwanza

I have conducted the following:
-Added the following validations:
-For the User model:
-Name must not be blank.
-PostsCounter must be an integer greater than or equal to zero.
-For the Post model:
Title must not be blank.
Title must not exceed 250 characters.
-CommentsCounter must be an integer greater than or equal to zero.
-LikesCounter must be an integer greater than or equal to zero.
-Added unit specs for all of your models' methods and validations.

2023-12-01 21:44 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Samuelwanza 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All tests are passing :heavy_check_mark: 
- Good validations in your models :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 21:44 UTC, tresorsawasawa commented on spec/user_spec.rb
> +end
- [ ] As required for the project to any custom methods in the models to have a corresponding unit test, kindly ensure that you also add tests to the `#recent_posts` method in the `User` model

2023-12-01 21:44 UTC, tresorsawasawa commented on spec/post_spec.rb
> +  it 'update_posts_counter should to function' do
- [ ] As required for the project to any custom methods in the models to have a corresponding unit test, kindly ensure that you also add tests to the `#recent_comments` method in the `User` model. Once you have added all the above changes, please ensure that all tests are still passing.

- [ **OPTIONAL** ] **RECOMMENDED:** I think it would be better if you create a directory such as `models` inside `spec` directory and move all your model tests files inside(`spec/models/...`) to make your files be organized and looks more professional.

2023-12-02 17:30 UTC, Efiamotu-1 approved these changes
Hi @Samuelwanza, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights :dart: 
* Correct Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝
[ OPTIONAL ] As  RECOMMENDED by the previous reviewer I think it would be better if you create a directory such as models inside spec directory and move all your model tests files inside(spec/models/...) to make your files be organized and looks more professional.

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 17:49 UTC, merged